config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  

  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'signup'  => 'user#new'
  get 'tournaments' => 'static_pages#tournament'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :user do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :images

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if logged_in?
  		@micropost = current_user.microposts.build 
  		@feed_items = current_user.feed.paginate(page: params[:page])
  	end
  end

  def tournament
    @image = Image.new
    @images = Image.paginate(page: params[:page])
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <body>
    <h1>About</h1>
    <p>
      This website is intended to serve as an information bulletin for all badminton related activities at the VG club house.
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact me at aviral2605@gmail.com & +91 7838873288
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <body>
    <h1>Vipul Greens Badminton</h1>
    <p>
      This is the help page for the VG Badminton website. (Under construction)
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
     <div class="col-md-8">
      <h3>Here's what everyone is saying</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to Vipul Greens Badminton</h1>

    <h2>
      This is a mini-tweet site!
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  
  <%= link_to image_tag("baddy.png", alt: "Badminton logo"),'http://www.bwfbadminton.org/', :target => "_blank" %>
<% end %>

app/views/static_pages/tournament.html.erb
<div>
    <aside>
        <h1 class = "bg-primary">31st July - 2nd August</h1> 
   	    <h1 class = "bg-secondary">Sweat it out to be the winner!</h1>
        <h3 class = "bg-secondary">You can upload pictures here! However, this page is under construction; some links may not work.</h3>
        <p align = "center">
            <button class = "pure-button"><%= link_to "Tournament-Rules", '#' %></button>
            <button class = "pure-button"><%= link_to "Teams", '#' %></button>
            <button class = "pure-button"><%= link_to "Scores", '#' %></button>
        </p>
        <h2> </h2>
        <aside class="col-md-4">
            <%= form_for(@image, html: {multipart: true}) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>
                <h3>Upload a picture here!</h3>
                <%= f.label :name %>
                <%= f.text_field :name, placeholder: "Give it a caption.." %>
                <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
                <%= f.hidden_field :timestamps, :value => DateTime.now %> 
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.submit "Post picture!" %>
            <% end %>
        </aside>
    </aside>    
</div>
<div class = "col-md-8">
  <% if @images && @images.any?%>
    
    <% for image in @images %>
        <h2>"<%=image.name%>"</h2>
        <h2>Posted <%= time_ago_in_words(image.timestamps) if image.timestamps%> ago by <%= User.find(image.user_id).name %></h2>
        <center><%=image_tag(image.picture.url)%></center>
        <h4> </h4>
        <!--<tr>
            <td><h2><%=image.name%> </h2></td>
            <td align = "center"><%=image_tag(image.picture.url)%></td>
        </tr>-->
    <% end %>
    <%= will_paginate @images %>
  <% end %>
</div>

  